name = "PDMPSamplers"
uuid = "7723e753-2147-4be3-a245-de95febc9fd4"
version = "0.1.0"
authors = ["Don van den Bergh <donvdbergh@hotmail.com>"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
BridgeStan = "c88b6f0a-829e-4b0b-94b7-f06ab5908f5a"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"

[extensions]
PDMPSamplersBridgeStanExt = "BridgeStan"
PDMPSamplersDynamicPPLExt = "DynamicPPL"

[compat]
ADTypes = "1"
DataStructures = "0.18, 0.19"
DifferentiationInterface = "0.7"
Distributions = "0.25"
FillArrays = "1"
Infiltrator = "1.9.3"
LinearAlgebra = "1.11.0"
LogExpFunctions = "0.3"
PDMats = "0.11.35"
ProgressMeter = "1.11"
QuadGK = "2"
Random = "1.11.0"
Roots = "2"
SpecialFunctions = "2"
Statistics = "1.11.1"
StatsBase = "0.34"
BridgeStan = "2"
DynamicPPL = "0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39"
julia = "1.12"
