[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
PDMPSamplers = "7723e753-2147-4be3-a245-de95febc9fd4"

[compat]
DocumenterVitepress = ">= 0.3"
